#!/usr/bin/env bash
# if nested

arch="School"

if [ -e $arch ]# -e verifica si el archivo existe
then
    echo "$arch file exists"

    if [ -s $arch ]
    then
	echo "$arch file is not empty"
    else
	echo "$arch file is empty"
    fi

    if [ -f $arch ]
    then
	echo "$arch is a regular file"
    fi
else
    echo "$arch file does not exist"
fi
